CREATE TYPE ROUNDING_TYPE AS ENUM ('CEIL', 'FLOOR', 'NEAREST');
CREATE TYPE STATISTICAL_OPERATION AS ENUM ('MEAN', 'MEDIAN');
CREATE TYPE ORDER_TYPE AS ENUM ('BUY', 'SELL', 'NONE');
CREATE TYPE BROADCASTING_STATUS AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE REQUEST_TYPE AS ENUM ('GET', 'POST');
CREATE TYPE PAYLOAD_TYPE AS ENUM ('JSON', 'FORM_DATA', 'URL_PARAMETERS', 'NONE');
CREATE TYPE SOURCE_STATUS AS ENUM ('UP', 'DOWN');
CREATE TYPE CURRENCY_TYPE AS ENUM ('FIAT', 'DIGITAL');
CREATE TYPE JSON_VALUE AS ENUM ('STRING', 'NUMBER', 'BOOLEAN', 'OBJECT', 'NULL');
